### ISSUE TITLE
pulledpork.py: command not found

### ISSUE THREAD

**Issue by Jakub41** [shirkdog/pulledpork3#41]
Hello,

On Ubuntu server v 20.04.3 LTS

I'm trying to install PulledPork with the instruction on the readme but when I try the command always I see this error

`pulledpork.py: command not found`

` /usr/bin/python3 /usr/local/bin/pulledpork/pulledpork.py -V`

Any of the commands suggested in the doc works for me.

Could you please tell me what should I do to have it correctly installed or what can be the issue?

Thank you for help

**Comment by NDietrich** [comment]
@Jakub41 if nothing was output when you ran that command then it sounds like you don't have PulledPork3 installed.
did you install PulledPork3 (not PulledPork2) following the guide:

`
cd ~/snort_src/
git clone https://github.com/shirkdog/pulledpork3.git


cd ~/snort_src/pulledpork3
sudo mkdir /usr/local/bin/pulledpork3
sudo cp pulledpork.py /usr/local/bin/pulledpork3
sudo cp -r lib/ /usr/local/bin/pulledpork3
sudo chmod +x /usr/local/bin/pulledpork3/pulledpork.py
sudo mkdir /usr/local/etc/pulledpork3
sudo cp etc/pulledpork.conf /usr/local/etc/pulledpork3/
`
