### ISSUE TITLE
correct setting for ruleset

### ISSUE THREAD

**Issue by aziel12** [shirkdog/pulledpork3#44]
Hello, I would like to use community and free registered rulesets. What is exactly LightSPD_ruleset? Does it contain community and registered rules (with SO rules) as well? Enabling all rulesets gives many overlaps warning. So, which ruleset contains most rules ?  Thanks
My config in pulledpork3:
community_ruleset=false
registered_ruleset=true
LightSPD_ruleset=false

**Comment by NDietrich** [comment]
Hello,
the Registerd and LighSPD rulesets are essentially the same, and those two also contain most of the community_ruleset as well.

My recomendation is to only use the LightSPD ruleset. it has the same rules as the registered ruleset but is more flexible when dealing with different versions of snort (easier from our point of view developing PP, and it's the direction that the Talos team is going long-term).  

The community ruleset has a lot of useless rules (looking for expoits for windows 98 systems for example), and anything important is included in the lightSPD ruelset.
