### ISSUE TITLE
422 Client Error: Unprocessable Entity for url

### ISSUE THREAD

**Issue by a937287837** [shirkdog/pulledpork3#45]
/usr/local/bin/pulledpork3/pulledpork.py -c /usr/local/etc/pulledpork3/pulledpork.conf

    https://github.com/shirkdog/pulledpork3
      _____ ____
     `----,\    )   PulledPork v3.0.0.2
      `--==\\  /    Lowcountry yellow mustard bbq sauce is the best bbq sauce. Fight me.
       `--==\\/
     .-~~~~-.Y|\\_  Copyright (C) 2021 Noah Dietrich, Colin Grady, Michael Shirk
  @_/        /  66\_  and the PulledPork Team!
    |    \   \   _(")
     \   /-| ||'--'   Rules give me wings!
      \_\  \_\\
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Loading configuration file:  /usr/local/etc/pulledpork3/pulledpork.conf
WARNING: Unable to load rules archive:  422 Client Error: Unprocessable Entity for url: https://snort.org/rules/snortrules-snapshot-3160.tar.gz?oinkcode=<hidden>

**Comment by NDietrich** [comment]
Talos never released a registered ruleset package for snort 3.1.6.0
you can either upgrade your snort to a newer version, specify a different version of snort in your pulledpork.conf (snort_version=3.1.5.0), or switch from registered to the LightSPD ruleset (my recomendation).
the lightSPD ruleset has rules for the different versions of snort, and PP3 can choose the best one for your install.
