### ISSUE TITLE
SyntaxWarning: "is" with a literal. Did you mean "=="? if type is 'enable', 'disable', 'drop'

### ISSUE THREAD

**Issue by snaybe** [shirkdog/pulledpork3#54]
When I verified the PulledPork3 via this code on Ubuntu "/usr/local/bin/pulledpork3/pulledpork.py -V" there is an error. Please see the picture below..

![image](https://user-images.githubusercontent.com/127446585/224153842-7fefe96e-8109-400a-9e99-c5e0d398f202.png)

I change the "is" to "==" and then the error was gone. The question is, is that necessary to change the "is" to "==" and is there effect when I changed it?

**Comment by mu5t3fa** [comment]
> 

Came to post this as well.

**Comment by colingrady** [comment]
Above PR merged.
